"""created_tables_column

Revision ID: ee2391f2546e
Revises: 342fe620a88d
Create Date: 2022-04-20 13:10:11.440353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2391f2546e'
down_revision = '342fe620a88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comments', ['id'])
    op.create_unique_constraint(None, 'like', ['id'])
    op.create_unique_constraint(None, 'posts', ['id'])
    op.add_column('user', sa.Column('block', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'block')
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_constraint(None, 'like', type_='unique')
    op.drop_constraint(None, 'comments', type_='unique')
    # ### end Alembic commands ###
